version: '2.3'
services:
  node-api:
    hostname: node-api
    image: valentinconan/node-api:master
    restart: unless-stopped
    env_file:
      - env/default.env
    healthcheck:
      test: wget -O /dev/null http://localhost:3000/api/ping || exit 1
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 3000:3000
    networks:
      - api-network
  node-api-native:
    hostname: node-api-native
    image: valentinconan/node-api-native:master
    restart: unless-stopped
    env_file:
      - env/default.env
    healthcheck:
      test: wget -O /dev/null http://localhost:3000/api/ping || exit 1
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 3001:3000
    networks:
      - api-network
networks:
  api-network:
    driver: bridge